In [1]:
import numpy as np

In [9]:
x = np.array([[1,2,3+4j,4,"5",1,2,3,4,5]])
print(type(x))
print(x)                                                     

<class 'numpy.ndarray'>
[['1' '2' '(3+4j)' '4' '5' '1' '2' '3' '4' '5']]


In [4]:
y = [1,2,3,4,5]
print(type(y))
print(y)

<class 'list'>
[1, 2, 3, 4, 5]


In [5]:
# <!-- Array -->

l = []

for i in range(1,5):
    int1 = int(input("Enter: "))
    l.append(int1)

print(np.array(l))

[ 12  12  13 114]


In [8]:
ar2 = np.array([[1,2,3,4],[1,2,3,4]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [9]:
ar3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [13]:
arn = np.array([1,2,3,4],ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [15]:
# <!-- Array with zeros -->

ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))

print(ar_zero)
print(" ")
print(ar_zero1)

[0. 0. 0. 0.]
 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


<!-- Array with ones -->

In [2]:
# <!-- Array with ones -->

ar_one = np.ones((4,5))
print(ar_one)
print(ar_one.ndim)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
2


In [5]:
# <!-- Empty Arrays -->

ar_em = np.empty(4)
print(ar_em)

[0.00000000e+000 1.06768667e-311 1.06768667e-311 1.06768667e-311]


In [6]:
# Range

ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


In [7]:
# Diagonal

ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
ar_dia = np.eye(3,5)
print(ar_dia)
print(ar_dia.ndim)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
2


In [13]:
# linspace

ar_lin = np.linspace(0,10, num=5)
print(ar_lin)

[ 0.   2.5  5.   7.5 10. ]


In [14]:
# Random 
# Rand()

var  = np.random.rand(4)
print(var)

[0.21939189 0.5009196  0.11318287 0.63650274]


In [31]:
var1  = np.random.rand(4,3)
print(var1)

[[0.4230937  0.16105309 0.72121271]
 [0.11604698 0.65603577 0.85133676]
 [0.03315323 0.20353531 0.24914568]
 [0.95253195 0.65796687 0.43410326]]


In [34]:
# randn()

var2  = np.random.randn(4)
print(var2)

[-0.72897445  0.87128005 -0.45298228  0.68767925]


In [36]:
# ranf()

var3  = np.random.ranf(4)
print(var3)

[0.07131679 0.0757469  0.19721138 0.59972918]


In [15]:
# randint()

var4  = np.random.randint(5,17,6)
print(var4)

[16  5  8  9  5  9]


In [46]:
#  Indexing

var = np.array([9,6,3,2])

print(var[1])
print(var[-1])

6
2


In [52]:
var1 = np.array([[1,2,3], [3,4,5]])
print(var1)
print(var1[1,1])

[[1 2 3]
 [3 4 5]]
4


In [59]:
# slicing

var = np.array([1,2,3,4,5,6,7,8])
print(var)
print()
print("Data from 3 to 6:", var[3:7])
print("Stop:", var[::2])

[1 2 3 4 5 6 7 8]

Data from 3 to 6: [4 5 6 7]
Stop: [1 3 5 7]


In [16]:
var1 = np.array([[1,2,3,4,5], [9,8,7,6,5], [11,12,13,14,15]])
print(var1)
print()
print("8 to 5:", var1[1,1:])

[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]

8 to 5: [8 7 6 5]


In [65]:
# Iteration

var = np.array([9,8,7,6,5,4])

for i in var:
    print(i)

9
8
7
6
5
4


In [151]:
var1 = np.array([[2,3,4,5],[6,7,8,9]])

for k in var1:
    for l in k:
        print(l)

2
3
4
5
6
7
8
9


In [71]:
var2 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])

print(var2)
print()

for i in var2:
    for j in i:
        for k in j:
            print(k)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]

1
2
3
4
5
6
7
8
9
10
11
12


In [73]:
var1 = np.array([[2,3,4,5],[6,7,8,9]])

for j in var1:
    print(j)

print()

for k in np.nditer(var1):
    print(k)

[2 3 4 5]
[6 7 8 9]

2
3
4
5
6
7
8
9


In [74]:
var1 = np.array([[2,3,4,5],[6,7,8,9]])

for j in var1:
    print(j)

print()

for k,d in np.ndenumerate(var1):
    print(k,d)

[2 3 4 5]
[6 7 8 9]

(0, 0) 2
(0, 1) 3
(0, 2) 4
(0, 3) 5
(1, 0) 6
(1, 1) 7
(1, 2) 8
(1, 3) 9


In [79]:
#  copy vs view

var = np.array([1,2,3,4])
co = var.copy()
var[1]= 23
print("data of var is:",var)
print("Copy of var is: ", co)

data of var is: [ 1 23  3  4]
Copy of var is:  [1 2 3 4]


In [81]:
x = np.array([1,2,3,4,5])
vi = x.view()
x[1]= 32
print("data of x is:",x)
print("View of x is: ",vi)

data of x is: [ 1 32  3  4  5]
View of x is:  [ 1 32  3  4  5]


In [84]:
# join array

var = np.array([1,2,3,4])
var1 = np.array([5,6,7,8])

arr = np.concatenate((var,var1))
print(arr)

[1 2 3 4 5 6 7 8]


In [2]:
import numpy as np

vr = np.array([[1,2],[3,4]])
vr1 = np.array([[5,6],[7,8]])
# print(vr)
ar = np.concatenate((vr,vr1),axis=1)
print(ar)

[[1 2 5 6]
 [3 4 7 8]]


In [92]:
var = np.array([1,2,3,4])
var1 = np.array([5,6,7,8])

arr = np.stack((var,var1),axis=0)
arr1 = np.hstack((var,var1)) #row
arr2 = np.vstack((var,var1)) #column
arr3 = np.dstack((var,var1)) #height

print(arr)
print()
print(arr1)
print()
print(arr2)
print()
print(arr3)


[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4 5 6 7 8]

[[1 2 3 4]
 [5 6 7 8]]

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


In [94]:
# split array

var = np.array([1,2,3,4,5,6,7,8,9])
ar = np.array_split(var, 3)
print(ar)
print(ar[0])

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[1 2 3]


In [96]:
# Search

var = np.array([1,2,3,2,1,4,5,6,7,4,3])

x = np.where(var == 2)
print(x)

(array([1, 3], dtype=int64),)


In [18]:
var1 = np.array([1,5,6,7])

x1 = np.searchsorted(var1, [5,3,4], side="right")
print(x1)

[2 1 1]


In [103]:
# Sort

var = np.array([2,3,10,1,4,5,6,7,14,3])
x = np.sort(var)
print(x)

[ 1  2  3  3  4  5  6  7 10 14]


In [106]:
var = np.array(["a","c","b","n","v", "p"])
x = np.sort(var)
print(x)

['a' 'b' 'c' 'n' 'p' 'v']


In [107]:
# filter array

var = np.array(["a","c","b","n","v", "p"])
f = [True, False, True, True, False, False]
new_a = var[f]

print(new_a)
print(type(new_a))

['a' 'b' 'n']
<class 'numpy.ndarray'>


In [108]:
# Arithmatic functions

var = np.array([1,2,3,4])
np.random.shuffle(var)
print(var)

[2 3 1 4]


In [110]:
var1 = np.array([1,2,3,4,2,5,4,2,2,7,5,5,9,4])
x= np.unique(var1, return_index=True, return_counts=True)
print(x)

(array([1, 2, 3, 4, 5, 7, 9]), array([ 0,  1,  2,  3,  5,  9, 12], dtype=int64), array([1, 4, 1, 3, 3, 1, 1], dtype=int64))


In [116]:
var2 = np.array([1,2,3,4,5,6])
y = np.resize(var2,(3,2))
print(y)
print()
print("Flatten:" ,y.flatten(order="F"))
print("Ravel: ", np.ravel(y, order="A"))

[[1 2]
 [3 4]
 [5 6]]

Flatten: [1 3 5 2 4 6]
Ravel:  [1 2 3 4 5 6]


In [4]:
# Insert & append

var = np.array([1,2,3,4])
print(var)
print(var.dtype)
v=np.insert(var, (2,3), 40)
x = np.append(var, 6.5)
print(x)
print(v)

[1 2 3 4]
int32
[1.  2.  3.  4.  6.5]
[ 1  2 40  3 40  4]


In [9]:
var1 = np.array([[1,2,3],[4,5,6]])

v1=np.insert(var1, 2, [21,2,2], axis=0)
print(v1)
print()
v1 = np.append(var1,[[45,44,23]], axis=0)
print(v1)

[[ 1  2  3]
 [ 4  5  6]
 [21  2  2]]

[[ 1  2  3]
 [ 4  5  6]
 [45 44 23]]


In [129]:
# Delete

var1 = np.array([1,2,3,4])
print(var1)
d=np.delete(var1,2)
print(d)

[1 2 3 4]
[1 2 4]


In [134]:
# Matrix

var = np.matrix([[1,2],[1,2]])
var1 = np.matrix([[1,2],[1,2]])

print(var)
print(type(var))
print()
print(var*var1)
print()
print(var.dot(var1))


[[1 2]
 [1 2]]
<class 'numpy.matrix'>

[[3 6]
 [3 6]]

[[3 6]
 [3 6]]


In [133]:
var = np.array([[1,2,3],[1,2,3]])
print(var)
print(type(var))

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


In [135]:
# Transpose

var =np.matrix([[1,2,3],[4,5,6]])
print(var)
print()
print(np.transpose(var))
print()
print(var.T)


[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [7]:
# Swapaxes

var =np.matrix([[1,2,3],[4,5,6]])
print(np.swapaxes(var,0,1))

[[1 4]
 [2 5]
 [3 6]]


In [139]:
# Inverse

var =np.matrix([[1,2],[3,4]])
print(var3)
print()
print(np.linalg.inv(var))

[0.07131679 0.0757469  0.19721138 0.59972918]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [140]:
# Power

var =np.matrix([[1,2],[3,4]])
print(var)
print()
print(np.linalg.matrix_power(var, 2))  
print()
print(np.linalg.matrix_power(var, 0))
print()
print(np.linalg.matrix_power(var, -2))
print()

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]



In [19]:
# Determinate

var =np.matrix([[1,4,3],[3,4,3],[1,2,3]])
print(var)
print()
print(np.linalg.det(var))

[[1 4 3]
 [3 4 3]
 [1 2 3]]

-12.000000000000005


In [10]:
var = np.array([[1,2], [3,4]])
print(var)
print()
var1 = np.array([[5,6], [7,8]])
print(var1)
print()
x = np.add(var,var1)
print(x)
print(np.ndim(var))


[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[ 6  8]
 [10 12]]
2
