In [91]:
import pandas as pd
import numpy as np

In [99]:
df = pd.read_json("C:/Users/Nishil Tejani/Downloads/cooler_on_15032024_145432283.json")
data = df["payload"]["values"]
print(data)

[[-66, 1030, 163], [-48, 1002, 122], [-75, 984, 129], [-28, 940, 119], [-20, 973, 88], [-60, 1045, 151], [-30, 1008, 109], [18, 988, 3], [-4, 962, -49], [-37, 956, -134], [-7, 964, -96], [-30, 1015, -26], [-15, 990, 95], [-72, 1042, 104], [-9, 965, 122], [-20, 1021, 25], [40, 965, -43], [-17, 949, -103], [-6, 983, -136], [-45, 948, -92], [-25, 957, 15], [-11, 1008, 54], [-24, 1012, 149], [7, 963, 95], [-10, 1008, 58], [-16, 984, -30], [0, 941, -88], [-20, 988, -101], [-40, 986, -39], [-27, 1033, 39], [-41, 977, 110], [-40, 993, 97], [25, 1004, 38], [-1, 1011, -41], [-47, 986, -111], [3, 974, -89], [-56, 979, -51], [-48, 966, 11], [-59, 1004, 131], [-33, 1001, 126], [-26, 985, 92], [23, 973, 15], [-22, 1003, -87], [21, 992, -116], [-37, 966, -85], [-53, 944, 3], [-34, 1007, 110], [-62, 1021, 155], [-17, 933, 88], [-19, 937, 66], [-8, 914, -32], [14, 889, -96], [-38, 957, -77], [-8, 951, -84], [-66, 962, 11], [-18, 980, 98], [-38, 991, 198], [-16, 1033, 107], [48, 983, 32], [-30, 928, -1

In [93]:
block_size = 100
step_size = 50
dfs = []
for i in range(0, len(data) - block_size + 1, step_size):
    start_index = i
    end_index = i + block_size
    block_df = data[start_index:end_index]
    print(block_df)
    dfs.append(block_df)

[[-66, 1030, 163], [-48, 1002, 122], [-75, 984, 129], [-28, 940, 119], [-20, 973, 88], [-60, 1045, 151], [-30, 1008, 109], [18, 988, 3], [-4, 962, -49], [-37, 956, -134], [-7, 964, -96], [-30, 1015, -26], [-15, 990, 95], [-72, 1042, 104], [-9, 965, 122], [-20, 1021, 25], [40, 965, -43], [-17, 949, -103], [-6, 983, -136], [-45, 948, -92], [-25, 957, 15], [-11, 1008, 54], [-24, 1012, 149], [7, 963, 95], [-10, 1008, 58], [-16, 984, -30], [0, 941, -88], [-20, 988, -101], [-40, 986, -39], [-27, 1033, 39], [-41, 977, 110], [-40, 993, 97], [25, 1004, 38], [-1, 1011, -41], [-47, 986, -111], [3, 974, -89], [-56, 979, -51], [-48, 966, 11], [-59, 1004, 131], [-33, 1001, 126], [-26, 985, 92], [23, 973, 15], [-22, 1003, -87], [21, 992, -116], [-37, 966, -85], [-53, 944, 3], [-34, 1007, 110], [-62, 1021, 155], [-17, 933, 88], [-19, 937, 66], [-8, 914, -32], [14, 889, -96], [-38, 957, -77], [-8, 951, -84], [-66, 962, 11], [-18, 980, 98], [-38, 991, 198], [-16, 1033, 107], [48, 983, 32], [-30, 928, -1

In [94]:
data1 = np.array(dfs)
print(data1)
print(len(data1))

[[[ -66 1030  163]
  [ -48 1002  122]
  [ -75  984  129]
  ...
  [ -67  974   24]
  [ -60 1044   71]
  [   3 1054   90]]

 [[  -8  914  -32]
  [  14  889  -96]
  [ -38  957  -77]
  ...
  [ -22  976 -100]
  [ -17  996    0]
  [ -36 1016  108]]

 [[  -2 1007  114]
  [ -13 1039   40]
  [   8 1024  -54]
  ...
  [ -28  936 -121]
  [ -31  926  -90]
  [ -43  935  -32]]

 ...

 [[  -4 1018  104]
  [   1  982    0]
  [ -42  941  -83]
  ...
  [  -7  933 -143]
  [ -32  951  -84]
  [ -46  992   44]]

 [[ -40  991  153]
  [ -40  971   73]
  [   0  913  -18]
  ...
  [   1 1005  -77]
  [ -14  956 -111]
  [  -7  966 -105]]

 [[ -63  976   10]
  [   0 1076  109]
  [ -36  997  111]
  ...
  [ -30 1000   81]
  [  11 1008  -20]
  [ -12  917 -107]]]
22


In [96]:
dfs = [pd.DataFrame(data_block, columns=['x', 'y', 'z']) for data_block in data1]

for i, df_block in enumerate(dfs):
    print(f"DataFrame {i}:")
    print(df_block)

DataFrame 0:
     x     y    z
0  -66  1030  163
1  -48  1002  122
2  -75   984  129
3  -28   940  119
4  -20   973   88
..  ..   ...  ...
95 -42   953 -128
96  22   967  -76
97 -67   974   24
98 -60  1044   71
99   3  1054   90

[100 rows x 3 columns]
DataFrame 1:
     x     y    z
0   -8   914  -32
1   14   889  -96
2  -38   957  -77
3   -8   951  -84
4  -66   962   11
..  ..   ...  ...
95  10   963  -53
96  56   957 -118
97 -22   976 -100
98 -17   996    0
99 -36  1016  108

[100 rows x 3 columns]
DataFrame 2:
     x     y    z
0   -2  1007  114
1  -13  1039   40
2    8  1024  -54
3  -40   943 -109
4  -32   905  -78
..  ..   ...  ...
95 -37   975  -29
96   1   891  -35
97 -28   936 -121
98 -31   926  -90
99 -43   935  -32

[100 rows x 3 columns]
DataFrame 3:
     x     y    z
0   -7  1036  124
1   -9   989  112
2    8  1003   -4
3    6   965  -64
4   47   941 -122
..  ..   ...  ...
95 -17   997  102
96  16   949   18
97 -32   998  -67
98  21   943 -144
99 -59   960 -116

[100 rows x

In [97]:
min_max_data = []
for df_block in dfs:
    min_values = df_block.min()
    max_values = df_block.max()
    min_max_data.append({
        'x_min': min_values['x'],
        'x_max': max_values['x'],
        'y_min': min_values['y'],
        'y_max': max_values['y'],
        'z_min': min_values['z'],
        'z_max': max_values['z']
    })

result_df = pd.DataFrame(min_max_data)

print(result_df)

    x_min  x_max  y_min  y_max  z_min  z_max
0     -78     48    889   1077   -147    198
1     -78     56    889   1077   -147    198
2     -91     57    879   1079   -144    172
3     -91     57    879   1079   -144    166
4     -88     47    895   1060   -161    169
5    -103     68    899   1065   -161    169
6    -103     78    889   1065   -139    183
7    -101     78    889   1059   -155    183
8    -101     42    890   1058   -168    170
9     -81     42    890   1079   -168    170
10    -81     31    902   1079   -150    179
11    -75     42    897   1060   -150    179
12    -88     60    891   1086   -137    163
13    -88     60    891   1086   -137    178
14    -94     51    838   1062   -144    178
15    -94     51    838   1050   -144    173
16    -91     42    860   1078   -124    173
17   -102     55    860   1078   -149    172
18   -102     55    907   1051   -156    164
19    -81     45    900   1061   -156    153
20   -104     45    900   1078   -147    153
21   -104 