In [25]:
import numpy as np

In [26]:
import pandas as pd

In [27]:
df = pd.read_json('C:/Users/Nishil Tejani/Downloads/cooler_on_15032024_145432283.json')

In [28]:
print(df)

                            protected         signature  \
ver                                v1  fBnO6BB537UYfrAS   
alg                             HS256  fBnO6BB537UYfrAS   
iat               15/03/2024-14:52:25  fBnO6BB537UYfrAS   
UID                               NaN  fBnO6BB537UYfrAS   
name                              NaN  fBnO6BB537UYfrAS   
type                              NaN  fBnO6BB537UYfrAS   
application_name                  NaN  fBnO6BB537UYfrAS   
interval_ms                       NaN  fBnO6BB537UYfrAS   
label                             NaN  fBnO6BB537UYfrAS   
sensors                           NaN  fBnO6BB537UYfrAS   
values                            NaN  fBnO6BB537UYfrAS   
duration                          NaN  fBnO6BB537UYfrAS   

                                                            payload  
ver                                                             NaN  
alg                                                             NaN  
iat                   

In [29]:
data=df["payload"]["values"]
print(data)

print(type(data))
print(len(data))

[[-66, 1030, 163], [-48, 1002, 122], [-75, 984, 129], [-28, 940, 119], [-20, 973, 88], [-60, 1045, 151], [-30, 1008, 109], [18, 988, 3], [-4, 962, -49], [-37, 956, -134], [-7, 964, -96], [-30, 1015, -26], [-15, 990, 95], [-72, 1042, 104], [-9, 965, 122], [-20, 1021, 25], [40, 965, -43], [-17, 949, -103], [-6, 983, -136], [-45, 948, -92], [-25, 957, 15], [-11, 1008, 54], [-24, 1012, 149], [7, 963, 95], [-10, 1008, 58], [-16, 984, -30], [0, 941, -88], [-20, 988, -101], [-40, 986, -39], [-27, 1033, 39], [-41, 977, 110], [-40, 993, 97], [25, 1004, 38], [-1, 1011, -41], [-47, 986, -111], [3, 974, -89], [-56, 979, -51], [-48, 966, 11], [-59, 1004, 131], [-33, 1001, 126], [-26, 985, 92], [23, 973, 15], [-22, 1003, -87], [21, 992, -116], [-37, 966, -85], [-53, 944, 3], [-34, 1007, 110], [-62, 1021, 155], [-17, 933, 88], [-19, 937, 66], [-8, 914, -32], [14, 889, -96], [-38, 957, -77], [-8, 951, -84], [-66, 962, 11], [-18, 980, 98], [-38, 991, 198], [-16, 1033, 107], [48, 983, 32], [-30, 928, -1

In [30]:
num_data = np.array(data)
print(num_data)

[[ -66 1030  163]
 [ -48 1002  122]
 [ -75  984  129]
 ...
 [ -13  990 -116]
 [ -14  912  -98]
 [ -49  967  -25]]


In [31]:
df = pd.DataFrame(num_data)
df

0     1    2
0    -66  1030  163
1    -48  1002  122
2    -75   984  129
3    -28   940  119
4    -20   973   88
...   ..   ...  ...
1191 -81  1038   79
1192  26   944  -59
1193 -13   990 -116
1194 -14   912  -98
1195 -49   967  -25

[1196 rows x 3 columns]

In [32]:
file = 'C:/Users/Nishil Tejani/Downloads/cooler_on'
df.to_csv('C:/Users/Nishil Tejani/Downloads/cooler_on.csv', index=False, header=False)

In [33]:
num_blocks = len(df) // 100

In [34]:
for i in range(num_blocks):
    start_index = i * 100
    end_index = start_index + 100
    block_df = df.iloc[start_index:end_index]

    block_file = f"C:/Users/Nishil Tejani/Downloads/block_{i + 1}.csv"
    block_df.to_csv(block_file, index=False, header=False)

In [35]:
remaining_data = len(df) % 100
if remaining_data > 0:
    remaining_block_df = df.iloc[-remaining_data:]
    remaining_block_file = f"C:/Users/Nishil Tejani/Downloads/block_{num_blocks + 1}.csv"
    remaining_block_df.to_csv(remaining_block_file, index=False, header=False)

min_values = df.min()
max_values = df.max()

for col in df.columns:
    print(f"Column '{col}': Min={min_values[col]}, Max={max_values[col]}")

Column '0': Min=-104, Max=78
Column '1': Min=838, Max=1086
Column '2': Min=-168, Max=198


In [36]:
block_max_values = {}
block_min_values = {}

for i in range(num_blocks):
    block_file = f"C:/Users/Nishil Tejani/Downloads/block_{i + 1}.csv"
    block_df = pd.read_csv(block_file, header=None)

    block_max_values[i] = {}
    block_min_values[i] = {}

    for column in block_df.columns:
        block_max_values[i][column] = block_df[column].max()
        block_min_values[i][column] = block_df[column].min()

for block_num, max_values in block_max_values.items():
    min_values = block_min_values[block_num]
    print(f"Block {block_num + 1}:")
    for column, max_val in max_values.items():
        min_val = min_values[column]
        print(f"  Column '{column}': Min={min_val}, Max={max_val}")

Block 1:
  Column '0': Min=-78, Max=48
  Column '1': Min=889, Max=1077
  Column '2': Min=-147, Max=198
Block 2:
  Column '0': Min=-91, Max=57
  Column '1': Min=879, Max=1079
  Column '2': Min=-144, Max=172
Block 3:
  Column '0': Min=-88, Max=47
  Column '1': Min=895, Max=1060
  Column '2': Min=-161, Max=169
Block 4:
  Column '0': Min=-103, Max=78
  Column '1': Min=889, Max=1065
  Column '2': Min=-139, Max=183
Block 5:
  Column '0': Min=-101, Max=42
  Column '1': Min=890, Max=1058
  Column '2': Min=-168, Max=170
Block 6:
  Column '0': Min=-81, Max=31
  Column '1': Min=902, Max=1079
  Column '2': Min=-150, Max=179
Block 7:
  Column '0': Min=-88, Max=60
  Column '1': Min=891, Max=1086
  Column '2': Min=-137, Max=163
Block 8:
  Column '0': Min=-94, Max=51
  Column '1': Min=838, Max=1062
  Column '2': Min=-144, Max=178
Block 9:
  Column '0': Min=-91, Max=42
  Column '1': Min=860, Max=1078
  Column '2': Min=-124, Max=173
Block 10:
  Column '0': Min=-102, Max=55
  Column '1': Min=907, Max=105