In [119]:
import pandas as pd
import numpy as np

In [128]:
df = pd.read_json('C:/Users/Nishil Tejani/Downloads/cooler_on_15032024_145432283.json')
df1 = pd.read_json('C:/Users/Nishil Tejani/Downloads/cooler_off_15032024_145723904.json')

data = df["payload"]["values"]
# print(len(data))
data1 = df1["payload"]["values"]
# print(len(data1))

# merged_data = np.concatenate((data, data1), axis=0)
# print(merged_data)
# print(len(merged_data))

In [129]:
block_size = 100
step_size = 50
dfs = []
for i in range(0, len(data) - block_size + 1, step_size):
    start_index = i
    end_index = i + block_size
    block_df = data[start_index:end_index]
    print(block_df)
    dfs.append(block_df)

[[-66, 1030, 163], [-48, 1002, 122], [-75, 984, 129], [-28, 940, 119], [-20, 973, 88], [-60, 1045, 151], [-30, 1008, 109], [18, 988, 3], [-4, 962, -49], [-37, 956, -134], [-7, 964, -96], [-30, 1015, -26], [-15, 990, 95], [-72, 1042, 104], [-9, 965, 122], [-20, 1021, 25], [40, 965, -43], [-17, 949, -103], [-6, 983, -136], [-45, 948, -92], [-25, 957, 15], [-11, 1008, 54], [-24, 1012, 149], [7, 963, 95], [-10, 1008, 58], [-16, 984, -30], [0, 941, -88], [-20, 988, -101], [-40, 986, -39], [-27, 1033, 39], [-41, 977, 110], [-40, 993, 97], [25, 1004, 38], [-1, 1011, -41], [-47, 986, -111], [3, 974, -89], [-56, 979, -51], [-48, 966, 11], [-59, 1004, 131], [-33, 1001, 126], [-26, 985, 92], [23, 973, 15], [-22, 1003, -87], [21, 992, -116], [-37, 966, -85], [-53, 944, 3], [-34, 1007, 110], [-62, 1021, 155], [-17, 933, 88], [-19, 937, 66], [-8, 914, -32], [14, 889, -96], [-38, 957, -77], [-8, 951, -84], [-66, 962, 11], [-18, 980, 98], [-38, 991, 198], [-16, 1033, 107], [48, 983, 32], [-30, 928, -1

In [130]:
block_size = 100
step_size = 50
dfs1 = []
for i in range(0, len(data1) - block_size + 1, step_size):
    start_index = i
    end_index = i + block_size
    block_df1 = data1[start_index:end_index]
    print(block_df1)
    dfs1.append(block_df1)

# print(len(block_df1))

[[3, 968, -25], [8, 977, -103], [14, 939, -97], [-65, 938, -78], [-44, 940, 11], [-21, 987, 1], [-15, 976, 1], [-17, 978, 11], [-18, 981, 21], [-31, 972, 2], [-15, 975, 10], [-9, 992, -1], [-19, 981, 5], [-23, 983, 5], [-17, 993, 6], [-17, 974, 10], [-14, 987, 8], [-20, 975, 15], [-17, 983, 14], [-25, 984, -3], [-25, 979, -2], [-22, 971, 15], [-13, 978, 1], [-26, 984, 1], [-27, 979, -10], [-15, 992, 11], [-16, 984, 8], [-32, 977, 0], [-24, 982, 3], [-11, 983, 5], [-15, 958, 11], [-28, 978, 8], [-27, 977, 10], [-22, 975, 13], [-31, 981, 14], [-16, 984, 12], [-29, 972, 7], [-21, 985, -1], [-8, 976, 16], [-21, 979, 15], [-27, 989, 5], [-32, 975, 7], [-24, 979, 13], [-35, 972, -1], [-19, 981, 0], [-20, 977, 0], [-30, 982, 7], [-29, 972, 0], [-18, 969, 6], [-17, 986, 3], [-26, 994, -1], [-29, 984, 12], [-24, 964, 10], [-17, 974, 0], [-17, 976, -6], [-17, 976, 8], [-30, 979, 4], [-18, 980, 5], [-27, 971, 3], [-18, 985, 1], [-11, 985, 0], [-22, 982, 4], [-16, 977, 0], [-28, 981, 5], [-23, 979

In [131]:
res_data = np.array(dfs)
print(res_data)
print(len(res_data))

print(np.shape(res_data))

[[[ -66 1030  163]
  [ -48 1002  122]
  [ -75  984  129]
  ...
  [ -67  974   24]
  [ -60 1044   71]
  [   3 1054   90]]

 [[  -8  914  -32]
  [  14  889  -96]
  [ -38  957  -77]
  ...
  [ -22  976 -100]
  [ -17  996    0]
  [ -36 1016  108]]

 [[  -2 1007  114]
  [ -13 1039   40]
  [   8 1024  -54]
  ...
  [ -28  936 -121]
  [ -31  926  -90]
  [ -43  935  -32]]

 ...

 [[  -4 1018  104]
  [   1  982    0]
  [ -42  941  -83]
  ...
  [  -7  933 -143]
  [ -32  951  -84]
  [ -46  992   44]]

 [[ -40  991  153]
  [ -40  971   73]
  [   0  913  -18]
  ...
  [   1 1005  -77]
  [ -14  956 -111]
  [  -7  966 -105]]

 [[ -63  976   10]
  [   0 1076  109]
  [ -36  997  111]
  ...
  [ -30 1000   81]
  [  11 1008  -20]
  [ -12  917 -107]]]
22
(22, 100, 3)


In [132]:
res_data1 = np.array(dfs1)
print(res_data1)
print(len(res_data1))

print(np.shape(res_data1))

[[[   3  968  -25]
  [   8  977 -103]
  [  14  939  -97]
  ...
  [ -23  985    4]
  [ -21  978    5]
  [ -20  981    3]]

 [[ -26  994   -1]
  [ -29  984   12]
  [ -24  964   10]
  ...
  [ -11  979    1]
  [ -23  985    3]
  [ -21  976    8]]

 [[ -24  981   11]
  [ -34  971    5]
  [ -18  984   11]
  ...
  [ -21  978   -6]
  [ -16  972    2]
  [ -20  986   -3]]

 ...

 [[ -22  974   11]
  [ -20  983   -6]
  [  -8  971    2]
  ...
  [ -20  986    8]
  [ -15  970    1]
  [ -23  983   10]]

 [[ -37  964   11]
  [ -15  990    3]
  [ -27  977    8]
  ...
  [ -14  985   -4]
  [ -23  972   -3]
  [ -21  975   -6]]

 [[ -26  980    7]
  [ -19  979    9]
  [ -21  981    2]
  ...
  [ -21  973    8]
  [ -26  980    5]
  [ -22  973    3]]]
23
(23, 100, 3)


In [133]:
merged_data = np.concatenate((res_data, res_data1), axis=0)
print(merged_data)
print(len(merged_data))

[[[ -66 1030  163]
  [ -48 1002  122]
  [ -75  984  129]
  ...
  [ -67  974   24]
  [ -60 1044   71]
  [   3 1054   90]]

 [[  -8  914  -32]
  [  14  889  -96]
  [ -38  957  -77]
  ...
  [ -22  976 -100]
  [ -17  996    0]
  [ -36 1016  108]]

 [[  -2 1007  114]
  [ -13 1039   40]
  [   8 1024  -54]
  ...
  [ -28  936 -121]
  [ -31  926  -90]
  [ -43  935  -32]]

 ...

 [[ -22  974   11]
  [ -20  983   -6]
  [  -8  971    2]
  ...
  [ -20  986    8]
  [ -15  970    1]
  [ -23  983   10]]

 [[ -37  964   11]
  [ -15  990    3]
  [ -27  977    8]
  ...
  [ -14  985   -4]
  [ -23  972   -3]
  [ -21  975   -6]]

 [[ -26  980    7]
  [ -19  979    9]
  [ -21  981    2]
  ...
  [ -21  973    8]
  [ -26  980    5]
  [ -22  973    3]]]
45


In [134]:
final_dfs = [pd.DataFrame(data_block, columns=['x', 'y', 'z']) for data_block in merged_data]

for i, df_block in enumerate(final_dfs):
    print(f"DataFrame {i}:")
    print(df_block)
# print(len(df_block))

DataFrame 0:
     x     y    z
0  -66  1030  163
1  -48  1002  122
2  -75   984  129
3  -28   940  119
4  -20   973   88
..  ..   ...  ...
95 -42   953 -128
96  22   967  -76
97 -67   974   24
98 -60  1044   71
99   3  1054   90

[100 rows x 3 columns]
DataFrame 1:
     x     y    z
0   -8   914  -32
1   14   889  -96
2  -38   957  -77
3   -8   951  -84
4  -66   962   11
..  ..   ...  ...
95  10   963  -53
96  56   957 -118
97 -22   976 -100
98 -17   996    0
99 -36  1016  108

[100 rows x 3 columns]
DataFrame 2:
     x     y    z
0   -2  1007  114
1  -13  1039   40
2    8  1024  -54
3  -40   943 -109
4  -32   905  -78
..  ..   ...  ...
95 -37   975  -29
96   1   891  -35
97 -28   936 -121
98 -31   926  -90
99 -43   935  -32

[100 rows x 3 columns]
DataFrame 3:
     x     y    z
0   -7  1036  124
1   -9   989  112
2    8  1003   -4
3    6   965  -64
4   47   941 -122
..  ..   ...  ...
95 -17   997  102
96  16   949   18
97 -32   998  -67
98  21   943 -144
99 -59   960 -116

[100 rows x

In [136]:
min_max_data = []
for df_block in final_dfs:
    min_values = df_block.min()
    max_values = df_block.max()
    min_max_data.append({
        'x_min': min_values['x'],
        'x_max': max_values['x'],
        'y_min': min_values['y'],
        'y_max': max_values['y'],
        'z_min': min_values['z'],
        'z_max': max_values['z']
    })

result_df = pd.DataFrame(min_max_data)
label_df = pd.DataFrame({
    'label': [df["payload"]["label"]] * len(res_data) + [df1["payload"]["label"]] * len(res_data1)
})

num_blocks = len(dfs)
label_df = pd.concat([label_df] * num_blocks, ignore_index=True)

result_df["label"] = label_df
print(result_df)

    x_min  x_max  y_min  y_max  z_min  z_max       label
0     -78     48    889   1077   -147    198   cooler_on
1     -78     56    889   1077   -147    198   cooler_on
2     -91     57    879   1079   -144    172   cooler_on
3     -91     57    879   1079   -144    166   cooler_on
4     -88     47    895   1060   -161    169   cooler_on
5    -103     68    899   1065   -161    169   cooler_on
6    -103     78    889   1065   -139    183   cooler_on
7    -101     78    889   1059   -155    183   cooler_on
8    -101     42    890   1058   -168    170   cooler_on
9     -81     42    890   1079   -168    170   cooler_on
10    -81     31    902   1079   -150    179   cooler_on
11    -75     42    897   1060   -150    179   cooler_on
12    -88     60    891   1086   -137    163   cooler_on
13    -88     60    891   1086   -137    178   cooler_on
14    -94     51    838   1062   -144    178   cooler_on
15    -94     51    838   1050   -144    173   cooler_on
16    -91     42    860   1078 